service: my-website-frontend

plugins:
  - serverless-finch

custom:
  client:
    bucketName: sushensatturu-com-frontend
    distributionFolder: out
    indexDocument: index.html
    errorDocument: 404.html

provider:
  name: aws
  region: ap-southeast-2
  profile: default